version: '3.1'

services:
  reverse-proxy:
    image: traefik # The official Traefik docker image
    command: --api --docker # Enables the web UI and tells Traefik to listen to docker
    ports:
      - "80:80"     # The HTTP port
      - "8080:8080" # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events

  blogbibliosistemas:
    image: wordpress
    labels:
      - "traefik.frontend.rule=Host:lab.draphp.com" #conecta traefic con el wordpress
    volumes:
      - ./html:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: blog
      WORDPRESS_DB_PASSWORD: myache
      WORDPRESS_DB_NAME: blog

  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 33006:3306 # expone el puerto  33006 afuera del contenedor

    environment:
      MYSQL_DATABASE: blog
      MYSQL_USER: blog
      MYSQL_PASSWORD: myache
      MYSQL_ROOT_PASSWORD: 'mapache'
    volumes:
      - /datos/mydata:/var/lib/mysql # crea un volumen que permite no perder los datos en los reinicios.
      - ./blog.sql.gz:/docker-entrypoint-initdb.d/backup.sql.gz #importa los datos al mysql desde un backup anterior del wordpress
